cobratag_test.go - fix golangci errors (unhandled error codes)
Add the error handling to all places where it was missing.
Which was quite a few.

One test case starts failing as a result of this, as an
error is now caught up.

--- PASS: TestCobraFieldsNoFlagProvided (0.00s)
=== RUN   TestCobraFieldsPersistent
    cobratag_test.go:160: Unexpected error in ParseFlags(argz = [secondcmd -v --extremelyimportant 88 --field4]): unknown flag: --extremelyimportant
--- FAIL: TestCobraFieldsPersistent (0.00s)