flaglookup.go - golintci-lint fixes
Fix these:

     ^
flaglookup.go:92:9: S1005: unnecessary assignment to the blank identifier (gosimple)
	for k, _ := range p.needflags {
	       ^

(Just remove the , _ ).

flaglookup.go:543:17: Error return value is not checked (errcheck)
						setFlagVal(parentpath, field.Name, fieldValue, tag, usagetag, existing)
						          ^

add err = setFlagVal..
There's an if right after that, which was already checking err.